#!/bin/bash
# ════════════════════════════════════════════════════════════════════════════
# GITOPS DEPLOYMENT SCRIPT
# Generated by Opsera Code-to-Cloud Enterprise v0.903
# 
# This script deploys the application using pure GitOps (ArgoCD)
# No GitHub Actions required - just run this script!
# ════════════════════════════════════════════════════════════════════════════

set -e

# Configuration
APP_NAME="event-demo-1"
TENANT="opsera"
HUB_CLUSTER="argocd-usw2"
SPOKE_CLUSTER="opsera-usw2-np"
AWS_REGION="us-west-2"
REPO_URL="https://github.com/Opsera-Test-M/testevent1.git"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║                     OPSERA GITOPS DEPLOYMENT                              ║"
echo "║                        Pure ArgoCD Approach                               ║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"
echo ""

# Check prerequisites
check_prerequisites() {
    echo -e "${BLUE}[1/6] Checking prerequisites...${NC}"
    
    if ! command -v kubectl &> /dev/null; then
        echo -e "${RED}❌ kubectl not found. Please install kubectl.${NC}"
        exit 1
    fi
    
    if ! command -v aws &> /dev/null; then
        echo -e "${RED}❌ AWS CLI not found. Please install AWS CLI.${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✅ All prerequisites met${NC}"
}

# Configure kubeconfig for hub cluster
configure_hub_cluster() {
    echo -e "${BLUE}[2/6] Configuring access to hub cluster (${HUB_CLUSTER})...${NC}"
    
    aws eks update-kubeconfig --name ${HUB_CLUSTER} --region ${AWS_REGION} --alias ${HUB_CLUSTER}
    
    # Verify connection
    if kubectl --context ${HUB_CLUSTER} get namespace argocd &> /dev/null; then
        echo -e "${GREEN}✅ Connected to hub cluster${NC}"
    else
        echo -e "${RED}❌ Cannot connect to hub cluster. Check AWS credentials.${NC}"
        exit 1
    fi
}

# Create repository secret
create_repo_secret() {
    echo -e "${BLUE}[3/6] Creating ArgoCD repository secret...${NC}"
    
    if [ -z "$GH_PAT" ]; then
        echo -e "${YELLOW}⚠️  GH_PAT environment variable not set${NC}"
        echo "Please set it: export GH_PAT=<your-github-personal-access-token>"
        read -p "Enter your GitHub PAT: " GH_PAT
    fi
    
    # Check if secret already exists
    if kubectl --context ${HUB_CLUSTER} get secret repo-${APP_NAME} -n argocd &> /dev/null; then
        echo -e "${YELLOW}⚠️  Repository secret already exists, updating...${NC}"
        kubectl --context ${HUB_CLUSTER} delete secret repo-${APP_NAME} -n argocd
    fi
    
    # Create the secret
    kubectl --context ${HUB_CLUSTER} create secret generic repo-${APP_NAME} \
        --namespace argocd \
        --from-literal=type=git \
        --from-literal=url="${REPO_URL}" \
        --from-literal=username=git \
        --from-literal=password="${GH_PAT}"
    
    kubectl --context ${HUB_CLUSTER} label secret repo-${APP_NAME} -n argocd \
        argocd.argoproj.io/secret-type=repository --overwrite
    
    echo -e "${GREEN}✅ Repository secret created${NC}"
}

# Verify spoke cluster is registered
verify_spoke_cluster() {
    echo -e "${BLUE}[4/6] Verifying spoke cluster registration...${NC}"
    
    if kubectl --context ${HUB_CLUSTER} get secret cluster-${SPOKE_CLUSTER} -n argocd &> /dev/null; then
        echo -e "${GREEN}✅ Spoke cluster ${SPOKE_CLUSTER} is registered with ArgoCD${NC}"
    else
        echo -e "${RED}❌ Spoke cluster ${SPOKE_CLUSTER} is NOT registered with ArgoCD${NC}"
        echo ""
        echo "Please register the spoke cluster first. Run:"
        echo "  kubectl --context ${SPOKE_CLUSTER} create serviceaccount argocd-manager -n kube-system"
        echo "  # Then create cluster secret in ArgoCD..."
        exit 1
    fi
}

# Deploy ArgoCD applications
deploy_argocd_apps() {
    local ENV=${1:-dev}
    
    echo -e "${BLUE}[5/6] Deploying ArgoCD Application for ${ENV}...${NC}"
    
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    APP_FILE="${SCRIPT_DIR}/argocd/${ENV}/application.yaml"
    
    if [ ! -f "$APP_FILE" ]; then
        echo -e "${RED}❌ Application file not found: ${APP_FILE}${NC}"
        exit 1
    fi
    
    kubectl --context ${HUB_CLUSTER} apply -f "${APP_FILE}"
    
    echo -e "${GREEN}✅ ArgoCD Application applied for ${ENV}${NC}"
}

# Wait for sync
wait_for_sync() {
    local ENV=${1:-dev}
    local TIMEOUT=300
    local ELAPSED=0
    
    echo -e "${BLUE}[6/6] Waiting for ArgoCD sync (timeout: ${TIMEOUT}s)...${NC}"
    
    while [ $ELAPSED -lt $TIMEOUT ]; do
        SYNC_STATUS=$(kubectl --context ${HUB_CLUSTER} get application ${APP_NAME}-${ENV} -n argocd \
            -o jsonpath='{.status.sync.status}' 2>/dev/null || echo "Unknown")
        
        HEALTH_STATUS=$(kubectl --context ${HUB_CLUSTER} get application ${APP_NAME}-${ENV} -n argocd \
            -o jsonpath='{.status.health.status}' 2>/dev/null || echo "Unknown")
        
        echo -e "  Sync: ${SYNC_STATUS} | Health: ${HEALTH_STATUS}"
        
        if [ "$SYNC_STATUS" == "Synced" ] && [ "$HEALTH_STATUS" == "Healthy" ]; then
            echo -e "${GREEN}✅ Application synced and healthy!${NC}"
            return 0
        fi
        
        sleep 10
        ELAPSED=$((ELAPSED + 10))
    done
    
    echo -e "${YELLOW}⚠️  Sync not complete within timeout. Check ArgoCD UI.${NC}"
}

# Main execution
main() {
    local ENV=${1:-dev}
    
    echo -e "${BLUE}Deploying ${APP_NAME} to ${ENV} environment${NC}"
    echo ""
    
    check_prerequisites
    configure_hub_cluster
    create_repo_secret
    verify_spoke_cluster
    deploy_argocd_apps ${ENV}
    wait_for_sync ${ENV}
    
    echo ""
    echo "════════════════════════════════════════════════════════════════════════════"
    echo -e "${GREEN}🎉 GitOps Deployment Complete!${NC}"
    echo ""
    echo "View in ArgoCD UI:"
    echo "  kubectl --context ${HUB_CLUSTER} port-forward svc/argocd-server -n argocd 8080:443"
    echo "  Open: https://localhost:8080"
    echo ""
    echo "Application URL (after DNS configured):"
    echo "  https://${TENANT}-${APP_NAME}-${ENV}.agent.opsera.dev"
    echo "════════════════════════════════════════════════════════════════════════════"
}

# Show usage
usage() {
    echo "Usage: $0 [environment]"
    echo ""
    echo "Environments:"
    echo "  dev      Deploy to DEV environment (default)"
    echo "  qa       Deploy to QA environment"
    echo "  staging  Deploy to STAGING environment"
    echo "  all      Deploy to ALL environments"
    echo ""
    echo "Examples:"
    echo "  $0           # Deploy to dev"
    echo "  $0 qa        # Deploy to qa"
    echo "  $0 all       # Deploy to all environments"
}

# Parse arguments
case "$1" in
    -h|--help)
        usage
        exit 0
        ;;
    all)
        check_prerequisites
        configure_hub_cluster
        create_repo_secret
        verify_spoke_cluster
        for env in dev qa staging; do
            deploy_argocd_apps $env
        done
        echo -e "${GREEN}✅ All environments deployed!${NC}"
        ;;
    *)
        main "${1:-dev}"
        ;;
esac
